spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgresql:
      jdbc-url: jdbc:postgresql://localhost/postgres
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver

  jackson:
    date-format: yyy-MM-dd
    time-zone: GMT+8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl